GET https://sprint-mission08-be.onrender.com/articles/c27619a7-a2fa-4b2f-ad4d-7925068e1d56/comments/cd5d5dd5-ac86-47b3-831a-89153cdcd1ea

###

GET http://localhost:5004/users/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e

###

POST http://localhost:5004/users
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5"
}

###

PATCH https://sprint-mission08-be.onrender.com/articles/c27619a7-a2fa-4b2f-ad4d-7925068e1d56/comments/cd5d5dd5-ac86-47b3-831a-89153cdcd1ea
Content-Type: application/json

{
  "resourceType": "ARTICLE",
  "resourceId": "c27619a7-a2fa-4b2f-ad4d-7925068e1d56",
  "content": "이 글 정말 유익하네요! 감사합니다."
}

###

DELETE http://localhost:5004/users/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
